CRTC equ 0

EFFECT_HEIGHT equ 251 -1 -6 - 6 + 3 ;+ 3;- 29


ENABLE_TAF equ 1
ENABLE_MUSIC equ 1
ENABLE_MAZE equ 1
ENABLE_SOUND_ANALYSIS equ 0
ENABLE_INTRO_SOUND equ 1

MAZE_MODE equ 1


WAIT_DURATION equ 6*50

BACKGROUND_INKA equ 14
BACKGROUND_INKB equ 15

BACKGROUND_INKA_COLOR equ GA_BLACK
BACKGROUND_INKB_COLOR equ GA_BLUE

BACKGROUND_INKA_COLOR_MIRROR equ GA_COL_10
BACKGROUND_INKB_COLOR_MIRROR equ GA_BLUE

PREPROCESS_BARS_PALETTES equ 0


