; AKY version 1.0, generated by Arkos Tracker 2.

; Header
 if !SIMPLIFY_4K
    db 0    ; Format version.
    db 3    ; How many channels are encoded.
 endif
; Frequency of the PSG index 0 (little endian): 1000000Hz.
    db 64, 66, 15, 0

Main_Subsong0_Linker:
; Pattern 0
Main_Subsong0_LinkerLoop:   ; Loops here.
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_0
    dw Main_Subsong0_Track_1
    dw Main_Subsong0_Track_2

; Pattern 1
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_0
    dw Main_Subsong0_Track_1
    dw Main_Subsong0_Track_2

; Pattern 2
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_0
    dw Main_Subsong0_Track_1
    dw Main_Subsong0_Track_2

; Pattern 3
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_0
    dw Main_Subsong0_Track_1
    dw Main_Subsong0_Track_2

; Pattern 4
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_12
    dw Main_Subsong0_Track_13
    dw Main_Subsong0_Track_2

; Pattern 5
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_15
    dw Main_Subsong0_Track_16
    dw Main_Subsong0_Track_2

; Pattern 6
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_42
    dw Main_Subsong0_Track_127
    dw Main_Subsong0_Track_146

; Pattern 7
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_42
    dw Main_Subsong0_Track_40
    dw Main_Subsong0_Track_146

; Pattern 8
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_42
    dw Main_Subsong0_Track_127
    dw Main_Subsong0_Track_146

; Pattern 9
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_42
    dw Main_Subsong0_Track_40
    dw Main_Subsong0_Track_146

; Pattern 10
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_30
    dw Main_Subsong0_Track_31
    dw Main_Subsong0_Track_146

; Pattern 11
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_33
    dw Main_Subsong0_Track_34
    dw Main_Subsong0_Track_146

; Pattern 12
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_42
    dw Main_Subsong0_Track_127
    dw Main_Subsong0_Track_146

; Pattern 13
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_42
    dw Main_Subsong0_Track_40
    dw Main_Subsong0_Track_146

; Pattern 14
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_42
    dw Main_Subsong0_Track_43
    dw Main_Subsong0_Track_146

; Pattern 15
    dw 72   ; Duration in frames.
    dw Main_Subsong0_Track_42
    dw Main_Subsong0_Track_121
    dw Main_Subsong0_Track_146

; Pattern 16
    dw 24   ; Duration in frames.
    dw Main_Subsong0_Track_84
    dw Main_Subsong0_Track_2
    dw Main_Subsong0_Track_50

; Pattern 17
    dw 96   ; Duration in frames.
    dw Main_Subsong0_Track_51
    dw Main_Subsong0_Track_52
    dw Main_Subsong0_Track_53

; Pattern 18
    dw 96   ; Duration in frames.
    dw Main_Subsong0_Track_51
    dw Main_Subsong0_Track_52
    dw Main_Subsong0_Track_53

; Pattern 19
    dw 96   ; Duration in frames.
    dw Main_Subsong0_Track_51
    dw Main_Subsong0_Track_52
    dw Main_Subsong0_Track_53

; Pattern 20
    dw 96   ; Duration in frames.
    dw Main_Subsong0_Track_51
    dw Main_Subsong0_Track_52
    dw Main_Subsong0_Track_53

; Pattern 21
    dw 96   ; Duration in frames.
    dw Main_Subsong0_Track_72
    dw Main_Subsong0_Track_73
    dw Main_Subsong0_Track_65

; Pattern 22
    dw 96   ; Duration in frames.
    dw Main_Subsong0_Track_72
    dw Main_Subsong0_Track_73
    dw Main_Subsong0_Track_74

; Pattern 23
    dw 96   ; Duration in frames.
    dw Main_Subsong0_Track_72
    dw Main_Subsong0_Track_73
    dw Main_Subsong0_Track_71

; Pattern 24
    dw 96   ; Duration in frames.
    dw Main_Subsong0_Track_72
    dw Main_Subsong0_Track_73
    dw Main_Subsong0_Track_74

; Pattern 25
    dw 96   ; Duration in frames.
    dw Main_Subsong0_Track_72
    dw Main_Subsong0_Track_73
    dw Main_Subsong0_Track_65

; Pattern 26
    dw 48   ; Duration in frames.
    dw Main_Subsong0_Track_72
    dw Main_Subsong0_Track_73
    dw Main_Subsong0_Track_80

; Pattern 27
    dw 48   ; Duration in frames.
    dw Main_Subsong0_Track_72
    dw Main_Subsong0_Track_73
    dw Main_Subsong0_Track_83

; Pattern 28
    dw 24   ; Duration in frames.
    dw Main_Subsong0_Track_84
    dw Main_Subsong0_Track_2
    dw Main_Subsong0_Track_50

; Pattern 29
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_96
    dw Main_Subsong0_Track_127
    dw Main_Subsong0_Track_146

; Pattern 30
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_96
    dw Main_Subsong0_Track_130
    dw Main_Subsong0_Track_146

; Pattern 31
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_96
    dw Main_Subsong0_Track_121
    dw Main_Subsong0_Track_146

; Pattern 32
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_96
    dw Main_Subsong0_Track_124
    dw Main_Subsong0_Track_146

; Pattern 33
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_141
    dw Main_Subsong0_Track_127
    dw Main_Subsong0_Track_146

; Pattern 34
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_141
    dw Main_Subsong0_Track_130
    dw Main_Subsong0_Track_146

; Pattern 35
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_141
    dw Main_Subsong0_Track_133
    dw Main_Subsong0_Track_146

; Pattern 36
    dw 72   ; Duration in frames.
    dw Main_Subsong0_Track_141
    dw Main_Subsong0_Track_124
    dw Main_Subsong0_Track_146

; Pattern 37
    dw 24   ; Duration in frames.
    dw Main_Subsong0_Track_141
    dw Main_Subsong0_Track_130
    dw Main_Subsong0_Track_146

; Pattern 38
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_135
    dw Main_Subsong0_Track_127
    dw Main_Subsong0_Track_146

; Pattern 39
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_135
    dw Main_Subsong0_Track_130
    dw Main_Subsong0_Track_146

; Pattern 40
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_135
    dw Main_Subsong0_Track_121
    dw Main_Subsong0_Track_146

; Pattern 41
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_135
    dw Main_Subsong0_Track_124
    dw Main_Subsong0_Track_146

; Pattern 42
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_135
    dw Main_Subsong0_Track_127
    dw Main_Subsong0_Track_146

; Pattern 43
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_135
    dw Main_Subsong0_Track_130
    dw Main_Subsong0_Track_146

; Pattern 44
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_135
    dw Main_Subsong0_Track_133
    dw Main_Subsong0_Track_146

; Pattern 45
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_135
    dw Main_Subsong0_Track_136
    dw Main_Subsong0_Track_146

; Pattern 46
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_141
    dw Main_Subsong0_Track_145
    dw Main_Subsong0_Track_146

; Pattern 47
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_141
    dw Main_Subsong0_Track_145
    dw Main_Subsong0_Track_146

; Pattern 48
    dw 84   ; Duration in frames.
    dw Main_Subsong0_Track_144
    dw Main_Subsong0_Track_145
    dw Main_Subsong0_Track_146

; Pattern 49
    dw 48   ; Duration in frames.
    dw Main_Subsong0_Track_144
    dw Main_Subsong0_Track_145
    dw Main_Subsong0_Track_146

; Pattern 50
    dw 24   ; Duration in frames.
    dw Main_Subsong0_Track_141
    dw Main_Subsong0_Track_124
    dw Main_Subsong0_Track_146

; Pattern 51
    dw 24   ; Duration in frames.
    dw Main_Subsong0_Track_141
    dw Main_Subsong0_Track_130
    dw Main_Subsong0_Track_146

; Pattern 52
    dw 24   ; Duration in frames.
    dw Main_Subsong0_Track_156
    dw Main_Subsong0_Track_127
    dw Main_Subsong0_Track_53

; Pattern 53
    dw 24   ; Duration in frames.
    dw Main_Subsong0_Track_156
    dw Main_Subsong0_Track_127
    dw Main_Subsong0_Track_74

; Pattern 54
    dw 24   ; Duration in frames.
    dw Main_Subsong0_Track_156
    dw Main_Subsong0_Track_127
    dw Main_Subsong0_Track_53

; Pattern 55
    dw 24   ; Duration in frames.
    dw Main_Subsong0_Track_156
    dw Main_Subsong0_Track_127
    dw Main_Subsong0_Track_74

    dw 0    ; Loops (duration = 0).
    dw Main_Subsong0_LinkerLoop

; The tracks.
Main_Subsong0_Track_50:
    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_0

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_1

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_2

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_90

Main_Subsong0_Track_156:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_5

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_6

Main_Subsong0_Track_84:
    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_8

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_9

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_10

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_131

Main_Subsong0_Track_80:
    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_13

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_106

Main_Subsong0_Track_83:
    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_13

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_94

Main_Subsong0_Track_12:
    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_22

Main_Subsong0_Track_13:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_141

    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_28

Main_Subsong0_Track_15:
    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_33

Main_Subsong0_Track_16:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_141

    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_39

Main_Subsong0_Track_30:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_20

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_22

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_28

Main_Subsong0_Track_31:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_50

Main_Subsong0_Track_33:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_31

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_33

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_39

Main_Subsong0_Track_34:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_61

Main_Subsong0_Track_40:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_63

Main_Subsong0_Track_42:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_133

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_72

Main_Subsong0_Track_43:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_74

Main_Subsong0_Track_96:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_76

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_96

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_78

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_76

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_96

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_78

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_76

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_96

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_78

Main_Subsong0_Track_121:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_86

Main_Subsong0_Track_124:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_88

Main_Subsong0_Track_127:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_90

Main_Subsong0_Track_130:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_92

Main_Subsong0_Track_133:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_94

Main_Subsong0_Track_135:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_96

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_118

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_76

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_96

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_118

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_76

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_96

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_118

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_76

Main_Subsong0_Track_136:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_106

Main_Subsong0_Track_141:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_108

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_118

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_76

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_108

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_118

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_76

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_108

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_118

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_76

Main_Subsong0_Track_144:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_118

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_119

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_108

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_118

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_119

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_108

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_118

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_119

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_108

Main_Subsong0_Track_145:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_128

Main_Subsong0_Track_0:
    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_133

Main_Subsong0_Track_1:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_141

    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 18   ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_131

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_72

Main_Subsong0_Track_2:
    db 84   ; Duration.
    dw Main_Subsong0_RegisterBlock_141

Main_Subsong0_Track_146:
    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_143

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_144

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_143

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_146

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_147

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_143

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_143

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_144

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_143

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_143

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_144

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_146

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_147

Main_Subsong0_Track_71:
    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_13

    db 36   ; Duration.
    dw Main_Subsong0_RegisterBlock_158

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_173

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_158

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_173

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_158

Main_Subsong0_Track_65:
    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_13

    db 36   ; Duration.
    dw Main_Subsong0_RegisterBlock_128

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_173

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_128

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_173

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_128

Main_Subsong0_Track_53:
    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_13

    db 36   ; Duration.
    dw Main_Subsong0_RegisterBlock_63

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_173

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_174

Main_Subsong0_Track_52:
    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_176

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_177

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_181

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_176

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_177

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_181

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_176

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_177

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_181

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_176

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_177

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_187

Main_Subsong0_Track_51:
    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_189

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_190

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_191

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_192

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_189

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_190

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_191

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_192

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_197

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_198

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_199

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_200

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_201

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_202

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_200

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_198

Main_Subsong0_Track_74:
    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_13

    db 36   ; Duration.
    dw Main_Subsong0_RegisterBlock_92

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_173

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_92

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_173

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_92

Main_Subsong0_Track_73:
    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_213

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_214

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_224

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_213

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_214

    db 12   ; Duration.
    dw Main_Subsong0_RegisterBlock_224

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_213

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_214

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_224

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_213

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_214

    db 24   ; Duration.
    dw Main_Subsong0_RegisterBlock_224

Main_Subsong0_Track_72:
    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_189

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_190

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_228

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_192

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_189

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_190

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_228

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_192

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_197

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_198

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_199

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_237

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_238

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_239

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_237

    db 6    ; Duration.
    dw Main_Subsong0_RegisterBlock_199


; The RegisterBlocks.
Main_Subsong0_RegisterBlock_50:
    db 121  ; Initial State: software only.
    db 204, 2   ; Software period.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 152  ; New LSB for software period.
    db 5    ; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_50_Loop:
    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 204  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 152  ; New LSB for software period.
    db 5    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_50_Loop


Main_Subsong0_RegisterBlock_61:
    db 121  ; Initial State: software only.
    db 246, 2   ; Software period.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 237  ; New LSB for software period.
    db 5    ; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_61_Loop:
    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 246  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 237  ; New LSB for software period.
    db 5    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_61_Loop


Main_Subsong0_RegisterBlock_63:
    db 121  ; Initial State: software only.
    db 63, 1    ; Software period.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 126  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_63_Loop:
    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 63   ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 126  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_63_Loop


Main_Subsong0_RegisterBlock_74:
    db 121  ; Initial State: software only.
    db 250, 1   ; Software period.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 244  ; New LSB for software period.
    db 3    ; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_74_Loop:
    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 250  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 244  ; New LSB for software period.
    db 3    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_74_Loop


Main_Subsong0_RegisterBlock_86:
    db 121  ; Initial State: software only.
    db 24, 2    ; Software period.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 49   ; New LSB for software period.
    db 4    ; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_86_Loop:
    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 24   ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 49   ; New LSB for software period.
    db 4    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_86_Loop


Main_Subsong0_RegisterBlock_88:
    db 121  ; Initial State: software only.
    db 222, 1   ; Software period.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 188  ; New LSB for software period.
    db 3    ; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_88_Loop:
    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 222  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 188  ; New LSB for software period.
    db 3    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_88_Loop


Main_Subsong0_RegisterBlock_90:
    db 121  ; Initial State: software only.
    db 126, 2   ; Software period.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 252  ; New LSB for software period.
    db 4    ; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_90_Loop:
    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 126  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 252  ; New LSB for software period.
    db 4    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_90_Loop


Main_Subsong0_RegisterBlock_92:
    db 121  ; Initial State: software only.
    db 170, 1   ; Software period.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 83   ; New LSB for software period.
    db 3    ; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_92_Loop:
    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 170  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 83   ; New LSB for software period.
    db 3    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_92_Loop


Main_Subsong0_RegisterBlock_94:
    db 121  ; Initial State: software only.
    db 102, 1   ; Software period.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 204  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_94_Loop:
    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 102  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 204  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_94_Loop


Main_Subsong0_RegisterBlock_106:
    db 121  ; Initial State: software only.
    db 123, 1   ; Software period.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 246  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_106_Loop:
    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 123  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 246  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_106_Loop


Main_Subsong0_RegisterBlock_128:
    db 121  ; Initial State: software only.
    db 146, 1   ; Software period.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 36   ; New LSB for software period.
    db 3    ; New MSB for software period, maybe with noise.

Main_Subsong0_RegisterBlock_128_Loop:
    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 146  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 36   ; New LSB for software period.
    db 3    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_128_Loop


Main_Subsong0_RegisterBlock_141:
    db 0    ; Initial State: no software, no hardware.

Main_Subsong0_RegisterBlock_141_Loop:
    db 4    ; Non-initial State, no software no hardware.

    db 8    ; Loop to index 1.
    dw Main_Subsong0_RegisterBlock_141_Loop


Main_Subsong0_RegisterBlock_158:
    db 121  ; Initial State: software only.
    db 195, 1   ; Software period.

Main_Subsong0_RegisterBlock_158_Loop:
    db 61   ; Non-initial State, software only.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 134  ; New LSB for software period.
    db 3    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 253  ; Non-initial State, software only.
    db 195  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 8    ; Loop to index 1.
    dw Main_Subsong0_RegisterBlock_158_Loop


Main_Subsong0_RegisterBlock_13:
    db 124  ; Initial State: no software, no hardware.
    db 16   ; Noise.

    db 244  ; Non-initial State, no software no hardware.
    db 17   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 18   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 19   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 20   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 21   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 22   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 23   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 24   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 25   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 26   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 27   ; Noise.

    db 252  ; Non-initial State, no software no hardware.
    db 16   ; Noise.

    db 244  ; Non-initial State, no software no hardware.
    db 17   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 18   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 19   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 20   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 21   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 22   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 23   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 24   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 25   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 26   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 27   ; Noise.


Main_Subsong0_RegisterBlock_14:
    db 121  ; Initial State: software only.
    db 123, 1   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_106 + 3   ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_17:
    db 121  ; Initial State: software only.
    db 102, 1   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_94 + 3    ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_20:
    db 121  ; Initial State: software only.
    db 179, 0   ; Software period.

    db 61   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 11   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 89   ; Software period, LSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 6    ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 253  ; Non-initial State, software only.
    db 102  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 245  ; Non-initial State, software only.
    db 179  ; New LSB for software period.
    db 0    ; New MSB for software period, maybe with noise.

    db 53   ; Non-initial State, software only.

    db 49   ; Non-initial State, software only.

    db 49   ; Non-initial State, software only.

    db 45   ; Non-initial State, software only.

    db 45   ; Non-initial State, software only.

    db 41   ; Non-initial State, software only.

    db 41   ; Non-initial State, software only.

    db 37   ; Non-initial State, software only.

    db 37   ; Non-initial State, software only.

    db 33   ; Non-initial State, software only.

    db 33   ; Non-initial State, software only.

    db 29   ; Non-initial State, software only.

    db 29   ; Non-initial State, software only.

    db 25   ; Non-initial State, software only.

    db 25   ; Non-initial State, software only.


Main_Subsong0_RegisterBlock_22:
    db 121  ; Initial State: software only.
    db 239, 0   ; Software period.

    db 61   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 15   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 119  ; Software period, LSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 7    ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 253  ; Non-initial State, software only.
    db 222  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 245  ; Non-initial State, software only.
    db 239  ; New LSB for software period.
    db 0    ; New MSB for software period, maybe with noise.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 21   ; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_31:
    db 121  ; Initial State: software only.
    db 190, 0   ; Software period.

    db 61   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 12   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 95   ; Software period, LSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 6    ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 253  ; Non-initial State, software only.
    db 123  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 245  ; Non-initial State, software only.
    db 190  ; New LSB for software period.
    db 0    ; New MSB for software period, maybe with noise.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 21   ; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_33:
    db 121  ; Initial State: software only.
    db 253, 0   ; Software period.

    db 61   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 16   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 127  ; Software period, LSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 8    ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 253  ; Non-initial State, software only.
    db 250  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 245  ; Non-initial State, software only.
    db 253  ; New LSB for software period.
    db 0    ; New MSB for software period, maybe with noise.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 21   ; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_131:
    db 121  ; Initial State: software only.
    db 159, 0   ; Software period.

    db 61   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 10   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 80   ; Software period, LSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 5    ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 253  ; Non-initial State, software only.
    db 63   ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 245  ; Non-initial State, software only.
    db 159  ; New LSB for software period.
    db 0    ; New MSB for software period, maybe with noise.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 21   ; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_133:
    db 121  ; Initial State: software only.
    db 213, 0   ; Software period.

    db 61   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 13   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 106  ; Software period, LSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 7    ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 253  ; Non-initial State, software only.
    db 170  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 245  ; Non-initial State, software only.
    db 213  ; New LSB for software period.
    db 0    ; New MSB for software period, maybe with noise.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 21   ; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_173:
    db 124  ; Initial State: no software, no hardware.
    db 1    ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 3    ; Noise.

    db 212  ; Non-initial State, no software no hardware.
    db 6    ; Noise.

    db 204  ; Non-initial State, no software no hardware.
    db 6    ; Noise.

    db 196  ; Non-initial State, no software no hardware.
    db 6    ; Noise.

    db 188  ; Non-initial State, no software no hardware.
    db 6    ; Noise.

Main_Subsong0_RegisterBlock_173_Loop:
    db 252  ; Non-initial State, no software no hardware.
    db 1    ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 3    ; Noise.

    db 212  ; Non-initial State, no software no hardware.
    db 6    ; Noise.

    db 204  ; Non-initial State, no software no hardware.
    db 6    ; Noise.

    db 196  ; Non-initial State, no software no hardware.
    db 6    ; Noise.

    db 188  ; Non-initial State, no software no hardware.
    db 6    ; Noise.

    db 8    ; Loop to index 6.
    dw Main_Subsong0_RegisterBlock_173_Loop


Main_Subsong0_RegisterBlock_174:
    db 117  ; Initial State: software only.
    db 15   ; Noise.
    db 152, 5   ; Software period.

    db 173  ; Non-initial State, software only.
    db 197  ; New MSB for software period, maybe with noise.
    db 16   ; New noise.

    db 165  ; Non-initial State, software only.
    db 197  ; New MSB for software period, maybe with noise.
    db 18   ; New noise.

    db 249  ; Non-initial State, software only.
    db 102  ; New LSB for software period.
    db 193  ; New MSB for software period, maybe with noise.
    db 20   ; New noise.

Main_Subsong0_RegisterBlock_174_Loop:
    db 185  ; Non-initial State, software only.
    db 193  ; New MSB for software period, maybe with noise.
    db 21   ; New noise.

    db 185  ; Non-initial State, software only.
    db 193  ; New MSB for software period, maybe with noise.
    db 23   ; New noise.

    db 249  ; Non-initial State, software only.
    db 204  ; New LSB for software period.
    db 194  ; New MSB for software period, maybe with noise.
    db 26   ; New noise.

    db 185  ; Non-initial State, software only.
    db 194  ; New MSB for software period, maybe with noise.
    db 30   ; New noise.

    db 249  ; Non-initial State, software only.
    db 102  ; New LSB for software period.
    db 193  ; New MSB for software period, maybe with noise.
    db 20   ; New noise.

    db 8    ; Loop to index 4.
    dw Main_Subsong0_RegisterBlock_174_Loop


Main_Subsong0_RegisterBlock_187:
    db 97   ; Initial State: software only.
    db 179, 0   ; Software period.

    db 109  ; Non-initial State, software only.
    db 176  ; New LSB for software period.

    db 105  ; Non-initial State, software only.
    db 182  ; New LSB for software period.

Main_Subsong0_RegisterBlock_187_Loop:
    db 113  ; Non-initial State, software only.
    db 179  ; New LSB for software period.

    db 109  ; Non-initial State, software only.
    db 176  ; New LSB for software period.

    db 105  ; Non-initial State, software only.
    db 182  ; New LSB for software period.

    db 8    ; Loop to index 3.
    dw Main_Subsong0_RegisterBlock_187_Loop


Main_Subsong0_RegisterBlock_224:
    db 89   ; Initial State: software only.
    db 134, 0   ; Software period.

    db 105  ; Non-initial State, software only.
    db 131  ; New LSB for software period.

    db 101  ; Non-initial State, software only.
    db 137  ; New LSB for software period.

Main_Subsong0_RegisterBlock_224_Loop:
    db 109  ; Non-initial State, software only.
    db 134  ; New LSB for software period.

    db 105  ; Non-initial State, software only.
    db 131  ; New LSB for software period.

    db 101  ; Non-initial State, software only.
    db 137  ; New LSB for software period.

    db 8    ; Loop to index 3.
    dw Main_Subsong0_RegisterBlock_224_Loop


Main_Subsong0_RegisterBlock_19:
    db 121  ; Initial State: software only.
    db 179, 0   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 3    ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_30:
    db 121  ; Initial State: software only.
    db 190, 0   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_31 + 3    ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_130:
    db 121  ; Initial State: software only.
    db 159, 0   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_131 + 3   ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_5:
    db 113  ; Initial State: software only.
    db 126, 2   ; Software period.

    db 117  ; Non-initial State, software only.
    db 123  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 129  ; New LSB for software period.

Main_Subsong0_RegisterBlock_5_Loop:
    db 121  ; Non-initial State, software only.
    db 126  ; New LSB for software period.

    db 117  ; Non-initial State, software only.
    db 123  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 129  ; New LSB for software period.

    db 8    ; Loop to index 3.
    dw Main_Subsong0_RegisterBlock_5_Loop


Main_Subsong0_RegisterBlock_6:
    db 113  ; Initial State: software only.
    db 126, 2   ; Software period.

    db 117  ; Non-initial State, software only.
    db 129  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 142  ; New LSB for software period.

    db 121  ; Non-initial State, software only.
    db 145  ; New LSB for software period.

    db 117  ; Non-initial State, software only.
    db 149  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 161  ; New LSB for software period.

    db 121  ; Non-initial State, software only.
    db 165  ; New LSB for software period.

    db 117  ; Non-initial State, software only.
    db 168  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 181  ; New LSB for software period.

    db 121  ; Non-initial State, software only.
    db 184  ; New LSB for software period.

    db 117  ; Non-initial State, software only.
    db 188  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 200  ; New LSB for software period.


Main_Subsong0_RegisterBlock_24:
    db 0    ; Initial State: no software, no hardware.

    db 8 : dw Main_Subsong0_RegisterBlock_141 + 1   ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_28:
    db 121  ; Initial State: software only.
    db 102, 1   ; Software period.

    db 61   ; Non-initial State, software only.

    db 127  ; Non-initial State, software and hardware.
    db 22   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 179  ; Software period, LSB.
    db 0    ; Software period, MSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 11   ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 253  ; Non-initial State, software only.
    db 204  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 245  ; Non-initial State, software only.
    db 102  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 21   ; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_39:
    db 121  ; Initial State: software only.
    db 123, 1   ; Software period.

    db 61   ; Non-initial State, software only.

    db 127  ; Non-initial State, software and hardware.
    db 24   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 190  ; Software period, LSB.
    db 0    ; Software period, MSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 12   ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 253  ; Non-initial State, software only.
    db 246  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 245  ; Non-initial State, software only.
    db 123  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 21   ; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_65:
    db 121  ; Initial State: software only.
    db 159, 0   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_131 + 3   ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_71:
    db 121  ; Initial State: software only.
    db 213, 0   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_133 + 3   ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_72:
    db 121  ; Initial State: software only.
    db 63, 1    ; Software period.

    db 61   ; Non-initial State, software only.

    db 127  ; Non-initial State, software and hardware.
    db 20   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 159  ; Software period, LSB.
    db 0    ; Software period, MSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 10   ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 253  ; Non-initial State, software only.
    db 126  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 61   ; Non-initial State, software only.

    db 245  ; Non-initial State, software only.
    db 63   ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 21   ; Optimization: goto common Block at index 9.

Main_Subsong0_RegisterBlock_76:
    db 113  ; Initial State: software only.
    db 159, 0   ; Software period.

    db 57   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 10   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 80   ; Software period, LSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 5    ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 249  ; Non-initial State, software only.
    db 63   ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 57   ; Non-initial State, software only.

    db 241  ; Non-initial State, software only.
    db 159  ; New LSB for software period.
    db 0    ; New MSB for software period, maybe with noise.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 23   ; Optimization: goto common Block at index 11.

Main_Subsong0_RegisterBlock_78:
    db 113  ; Initial State: software only.
    db 63, 1    ; Software period.

    db 57   ; Non-initial State, software only.

    db 127  ; Non-initial State, software and hardware.
    db 20   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 159  ; Software period, LSB.
    db 0    ; Software period, MSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 10   ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 249  ; Non-initial State, software only.
    db 126  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 57   ; Non-initial State, software only.

    db 241  ; Non-initial State, software only.
    db 63   ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 23   ; Optimization: goto common Block at index 11.

Main_Subsong0_RegisterBlock_96:
    db 113  ; Initial State: software only.
    db 213, 0   ; Software period.

    db 57   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 13   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 106  ; Software period, LSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 7    ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 249  ; Non-initial State, software only.
    db 170  ; New LSB for software period.
    db 1    ; New MSB for software period, maybe with noise.

    db 57   ; Non-initial State, software only.

    db 241  ; Non-initial State, software only.
    db 213  ; New LSB for software period.
    db 0    ; New MSB for software period, maybe with noise.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 23   ; Optimization: goto common Block at index 11.

Main_Subsong0_RegisterBlock_108:
    db 113  ; Initial State: software only.
    db 80, 0    ; Software period.

    db 57   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 5    ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 40   ; Software period, LSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 3    ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 121  ; Non-initial State, software only.
    db 159  ; New LSB for software period.

    db 57   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 80   ; New LSB for software period.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 23   ; Optimization: goto common Block at index 11.

Main_Subsong0_RegisterBlock_118:
    db 113  ; Initial State: software only.
    db 106, 0   ; Software period.

    db 57   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 7    ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 53   ; Software period, LSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 3    ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 121  ; Non-initial State, software only.
    db 213  ; New LSB for software period.

    db 57   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 106  ; New LSB for software period.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 23   ; Optimization: goto common Block at index 11.

Main_Subsong0_RegisterBlock_144:
    db 124  ; Initial State: no software, no hardware.
    db 1    ; Noise.

    db 193  ; Non-initial State, software only.
    db 126  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.

    db 252  ; Non-initial State, no software no hardware.
    db 1    ; Noise.

Main_Subsong0_RegisterBlock_144_Loop:
    db 1    ; Non-initial State, software only.

    db 8    ; Loop to index 7.
    dw Main_Subsong0_RegisterBlock_144_Loop


Main_Subsong0_RegisterBlock_181:
    db 97   ; Initial State: software only.
    db 127, 0   ; Software period.

    db 109  ; Non-initial State, software only.
    db 124  ; New LSB for software period.

    db 105  ; Non-initial State, software only.
    db 130  ; New LSB for software period.

Main_Subsong0_RegisterBlock_181_Loop:
    db 113  ; Non-initial State, software only.
    db 127  ; New LSB for software period.

    db 109  ; Non-initial State, software only.
    db 124  ; New LSB for software period.

    db 105  ; Non-initial State, software only.
    db 130  ; New LSB for software period.

    db 8    ; Loop to index 3.
    dw Main_Subsong0_RegisterBlock_181_Loop


Main_Subsong0_RegisterBlock_218:
    db 89   ; Initial State: software only.
    db 134, 0   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_224 + 3   ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_0:
    db 81   ; Initial State: software only.
    db 246, 2   ; Software period.

    db 41   ; Non-initial State, software only.

    db 41   ; Non-initial State, software only.

    db 233  ; Non-initial State, software only.
    db 237  ; New LSB for software period.
    db 5    ; New MSB for software period, maybe with noise.

    db 41   ; Non-initial State, software only.

    db 233  ; Non-initial State, software only.
    db 246  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.


Main_Subsong0_RegisterBlock_1:
    db 97   ; Initial State: software only.
    db 204, 2   ; Software period.

    db 49   ; Non-initial State, software only.

    db 49   ; Non-initial State, software only.

    db 241  ; Non-initial State, software only.
    db 152  ; New LSB for software period.
    db 5    ; New MSB for software period, maybe with noise.

    db 49   ; Non-initial State, software only.

    db 241  ; Non-initial State, software only.
    db 204  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.


Main_Subsong0_RegisterBlock_2:
    db 113  ; Initial State: software only.
    db 164, 2   ; Software period.

    db 57   ; Non-initial State, software only.

    db 57   ; Non-initial State, software only.

    db 249  ; Non-initial State, software only.
    db 71   ; New LSB for software period.
    db 5    ; New MSB for software period, maybe with noise.

    db 57   ; Non-initial State, software only.

    db 249  ; Non-initial State, software only.
    db 164  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.


Main_Subsong0_RegisterBlock_3:
    db 121  ; Initial State: software only.
    db 126, 2   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_90 + 3    ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_8:
    db 81   ; Initial State: software only.
    db 190, 0   ; Software period.

    db 41   ; Non-initial State, software only.

    db 8 : dw Main_Subsong0_RegisterBlock_31 + 4    ; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_9:
    db 97   ; Initial State: software only.
    db 179, 0   ; Software period.

    db 49   ; Non-initial State, software only.

    db 8 : dw Main_Subsong0_RegisterBlock_20 + 4    ; Optimization: goto common Block at index 2.

Main_Subsong0_RegisterBlock_10:
    db 113  ; Initial State: software only.
    db 169, 0   ; Software period.

    db 57   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 11   ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 84   ; Software period, LSB.
    db 8    ; Hardware period.

    db 8 : dw Main_Subsong0_RegisterBlock_131 + 9   ; Optimization: goto common Block at index 3.

Main_Subsong0_RegisterBlock_11:
    db 121  ; Initial State: software only.
    db 159, 0   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_131 + 3   ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_77:
    db 113  ; Initial State: software only.
    db 213, 0   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_96 + 3    ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_97:
    db 113  ; Initial State: software only.
    db 106, 0   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_118 + 3   ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_119:
    db 113  ; Initial State: software only.
    db 53, 0    ; Software period.

    db 57   ; Non-initial State, software only.

    db 95   ; Non-initial State, software and hardware.
    db 3    ; Hardware period, LSB.
    db 0    ; Hardware period, MSB.
    db 27   ; Software period, LSB.
    db 8    ; Hardware period.

    db 3    ; Non-initial State, software and hardware.

    db 71   ; Non-initial State, software and hardware.
    db 2    ; Hardware period, LSB.
    db 10   ; Hardware period.

    db 3    ; Non-initial State, software and hardware.


Main_Subsong0_RegisterBlock_143:
    db 125  ; Initial State: software only.
    db 30   ; Noise.
    db 126, 2   ; Software period.

    db 244  ; Non-initial State, no software no hardware.
    db 13   ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 19   ; Noise.

    db 233  ; Non-initial State, software only.
    db 137  ; New LSB for software period.
    db 194  ; New MSB for software period, maybe with noise.
    db 14   ; New noise.

    db 204  ; Non-initial State, no software no hardware.
    db 9    ; Noise.

    db 4    ; Non-initial State, no software no hardware.


Main_Subsong0_RegisterBlock_146:
    db 124  ; Initial State: no software, no hardware.
    db 19   ; Noise.

    db 244  ; Non-initial State, no software no hardware.
    db 4    ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 5    ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 7    ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 9    ; Noise.

    db 236  ; Non-initial State, no software no hardware.
    db 10   ; Noise.


Main_Subsong0_RegisterBlock_147:
    db 124  ; Initial State: no software, no hardware.
    db 1    ; Noise.

    db 193  ; Non-initial State, software only.
    db 126  ; New LSB for software period.
    db 2    ; New MSB for software period, maybe with noise.

    db 1    ; Non-initial State, software only.

    db 244  ; Non-initial State, no software no hardware.
    db 1    ; Noise.

    db 1    ; Non-initial State, software only.

    db 1    ; Non-initial State, software only.


Main_Subsong0_RegisterBlock_159:
    db 124  ; Initial State: no software, no hardware.
    db 1    ; Noise.

    db 8 : dw Main_Subsong0_RegisterBlock_173 + 2   ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_176:
    db 97   ; Initial State: software only.
    db 159, 0   ; Software period.

    db 109  ; Non-initial State, software only.
    db 156  ; New LSB for software period.

    db 105  ; Non-initial State, software only.
    db 162  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 159  ; New LSB for software period.

    db 109  ; Non-initial State, software only.
    db 156  ; New LSB for software period.

    db 105  ; Non-initial State, software only.
    db 162  ; New LSB for software period.


Main_Subsong0_RegisterBlock_177:
    db 97   ; Initial State: software only.
    db 142, 0   ; Software period.

    db 109  ; Non-initial State, software only.
    db 139  ; New LSB for software period.

    db 105  ; Non-initial State, software only.
    db 145  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 142  ; New LSB for software period.

    db 109  ; Non-initial State, software only.
    db 139  ; New LSB for software period.

    db 105  ; Non-initial State, software only.
    db 145  ; New LSB for software period.


Main_Subsong0_RegisterBlock_178:
    db 97   ; Initial State: software only.
    db 127, 0   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_181 + 3   ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_189:
    db 97   ; Initial State: software only.
    db 27, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 53   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 50   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 53   ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 50   ; New LSB for software period.


Main_Subsong0_RegisterBlock_190:
    db 97   ; Initial State: software only.
    db 30, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 60   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 57   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 60   ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 57   ; New LSB for software period.


Main_Subsong0_RegisterBlock_191:
    db 97   ; Initial State: software only.
    db 32, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 63   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 60   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 63   ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 60   ; New LSB for software period.


Main_Subsong0_RegisterBlock_192:
    db 97   ; Initial State: software only.
    db 40, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 80   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 77   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 80   ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 77   ; New LSB for software period.


Main_Subsong0_RegisterBlock_197:
    db 97   ; Initial State: software only.
    db 45, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 89   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 86   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 89   ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 86   ; New LSB for software period.


Main_Subsong0_RegisterBlock_198:
    db 97   ; Initial State: software only.
    db 53, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 106  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 103  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 106  ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 103  ; New LSB for software period.


Main_Subsong0_RegisterBlock_199:
    db 97   ; Initial State: software only.
    db 60, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 119  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 116  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 119  ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 116  ; New LSB for software period.


Main_Subsong0_RegisterBlock_200:
    db 97   ; Initial State: software only.
    db 63, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 127  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 124  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 127  ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 124  ; New LSB for software period.


Main_Subsong0_RegisterBlock_201:
    db 97   ; Initial State: software only.
    db 89, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 179  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 176  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 179  ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 176  ; New LSB for software period.


Main_Subsong0_RegisterBlock_202:
    db 97   ; Initial State: software only.
    db 75, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 150  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 147  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 150  ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 147  ; New LSB for software period.


Main_Subsong0_RegisterBlock_213:
    db 89   ; Initial State: software only.
    db 159, 0   ; Software period.

    db 105  ; Non-initial State, software only.
    db 156  ; New LSB for software period.

    db 101  ; Non-initial State, software only.
    db 162  ; New LSB for software period.

    db 109  ; Non-initial State, software only.
    db 159  ; New LSB for software period.

    db 105  ; Non-initial State, software only.
    db 156  ; New LSB for software period.

    db 101  ; Non-initial State, software only.
    db 162  ; New LSB for software period.


Main_Subsong0_RegisterBlock_214:
    db 89   ; Initial State: software only.
    db 142, 0   ; Software period.

    db 105  ; Non-initial State, software only.
    db 139  ; New LSB for software period.

    db 101  ; Non-initial State, software only.
    db 145  ; New LSB for software period.

    db 109  ; Non-initial State, software only.
    db 142  ; New LSB for software period.

    db 105  ; Non-initial State, software only.
    db 139  ; New LSB for software period.

    db 101  ; Non-initial State, software only.
    db 145  ; New LSB for software period.


Main_Subsong0_RegisterBlock_215:
    db 89   ; Initial State: software only.
    db 134, 0   ; Software period.

    db 8 : dw Main_Subsong0_RegisterBlock_224 + 3   ; Optimization: goto common Block at index 1.

Main_Subsong0_RegisterBlock_228:
    db 97   ; Initial State: software only.
    db 34, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 67   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 64   ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 67   ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 64   ; New LSB for software period.


Main_Subsong0_RegisterBlock_237:
    db 97   ; Initial State: software only.
    db 67, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 134  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 131  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 134  ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 131  ; New LSB for software period.


Main_Subsong0_RegisterBlock_238:
    db 97   ; Initial State: software only.
    db 80, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 159  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 156  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 159  ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 156  ; New LSB for software period.


Main_Subsong0_RegisterBlock_239:
    db 97   ; Initial State: software only.
    db 71, 0    ; Software period.

    db 113  ; Non-initial State, software only.
    db 142  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 139  ; New LSB for software period.

    db 113  ; Non-initial State, software only.
    db 142  ; New LSB for software period.

    db 49   ; Non-initial State, software only.

    db 113  ; Non-initial State, software only.
    db 139  ; New LSB for software period.


